version: "3"

services:
  ghost:
    restart: always
    image: ghost:4
    environment:
      - url="https://argonaut.network"
    networks:
      - proxy
    volumes:
      - /var/lib/ghost/content:/var/lib/ghost/content
    labels:
    - traefik.enable=true
    - traefik.http.routers.ghost-cms-argonaut-network-secure.entrypoints=https
    - traefik.http.routers.ghost-cms-argonaut-network-secure.rule=Host(`argonaut.network`)
    - traefik.http.routers.ghost-cms-argonaut-network-secure.tls=true

    - com.centurylinklabs.watchtower.enable=true

networks:
  proxy:
    external: true
